services:
  localstack:
    image: localstack/localstack:4
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN
      SERVICES: sns,sqs
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3

  mongodb:
    image: mongo:6.0.13
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: unless-stopped

  gmr-finder:
    build:
      args:
        DEFRA_NUGET_PAT: ${DEFRA_NUGET_PAT}
      context: ./
    ports:
      - '8080:8080'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
      - '.env'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      GvmsApi__ClientId: ${GVMS_API_CLIENT_ID}
      GvmsApi__ClientSecret: ${GVMS_API_CLIENT_SECRET}
      Mongo__DatabaseUri: mongodb://mongodb:27017/
      PORT: 8080
      SNS_ENDPOINT: http://localstack:4566
      SQS_ENDPOINT: http://localstack:4566
      USE_LOCALSTACK: true

volumes:
  mongodb-data:
