name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Test
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0
      - name: Update NuGet.config
        run: |
          dotnet nuget remove source defra
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name defra "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --configfile NuGet.config
      - name: Run unit tests
        run: |
          dotnet test --filter "Category!=IntegrationTests"
      - name: Run integration tests
        env:
          GVMS_API_CLIENT_ID: ${{ secrets.GVMS_API_CLIENT_ID }}
          GVMS_API_CLIENT_SECRET: ${{ secrets.GVMS_API_CLIENT_SECRET }}
        run: |
          touch .env
          docker compose up -d
          dotnet test --filter "Category=IntegrationTests"
      - name: Docker Compose Logs
        if: always()
        run: |
          docker compose logs
      - name: Check Dockerfile Builds
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: trade-imports-gmr-finder:latest
      - name: Check with Trivy
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image trade-imports-gmr-finder:latest --ignore-unfixed
  sonarcloud-scan:
    name: CDP SonarCloud Scan
    uses: ./.github/workflows/sonarcloud.yml
    needs: pr-validator
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
